[package]
name = "casbin"
version = "0.1.5"
authors = ["Joey <joey.xf@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "An authorization library that supports access control models like ACL, RBAC, ABAC."
homepage = "https://casbin.org/"
repository = "https://github.com/casbin/casbin-rs"
readme = "README.md"
keywords = ["auth", "authorization", "rbac", "acl", "abac"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
rhai = "0.9.1"
ip_network = "0.3.4"
ttl_cache = "0.5.1"
emitbrown = "0.1.8"
lazy_static = "1.4.0"
indexmap = "1.3.1"

[profile.release.build-override]
opt-level = 0
